name = "curlify_wisp"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
curlify = { path = "../" }
wisp = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
